### ISSUE TITLE
No escoger distrito electoral no debe llevar a error

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/open-wizard#101]
Si el usario no elige ningun distrito electoral, en vez de seguir a la siguiente pregunta, debe aparecer el Mensaje de error: 
**Para empezar, elige dónde votas**

Considerar opcion de desactivar el botón de continuar si no se ha escogido "location", o quitar la opción que dice "Seleccione uno" y arrancar por Amazonas nomás.

**Comment by wixo** [comment]
closed in #219
