### ISSUE TITLE
Actualizacion de resultados

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#103]
En local storage trae los candidatos correctos del API pero no esta volviendo a sobreescribir lo que se muestra. Solo cuando hago refresh me funciona.

**Comment by gianpietro1** [comment]
@wixo vi que desactivar SSR no arreglaba el problema, finalmente después de probar e investigar encontré esto:

- El componente no re-rendereaba porque no había nada que dependiera explícitamente de "data", sino la función showPartyCards que dependía de filteredCandidates (ls), que a su vez dependía de la data. Parece que esta cadena de dependencias no permitía que el rendering ocurra al actualizarse "data".
- En ocasiones "data" no se actualizaba (no había fetch), encontré que para forzar esto, había que pasarle a useSWR un key único cada vez, es decir, que dependiera de los apiTerms que cambiaban con cada visita.

Finalmente los cambios serán: 
1. Hacer que showPartyCards dependa directamente de "data" para forzar el rendering.

```
        <Styled.Results>
          {showPartyCards(
            groupCandidatesByPartyNameAndLS(data?.data.candidates),
          )}
        </Styled.Results>
```

2. Cambiar el key de useSWR para que cambie con los parámetros del fetch, para así forzar siempre un re-fetch.

```
const fetchCandidates = () => {
  const apiTerms = qs.stringify(mapApiTerms(ls('op.wizard')));
  const { data, error } = useSWR(`/api/candidates?${apiTerms}`, () =>
    fetch(`${process.env.api.candidatesUrl}?${apiTerms}`).then((data) =>
      data.json(),
    ),
  );
  return data;
};
```
