### ISSUE TITLE
Pantalla de partidos 

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#13]
Una vez que el usuario responde las preguntas bases, le mostramos los candidatos pero ordenados por partidos. 
![Screenshot 2021-01-16 at 22 56 21](https://user-images.githubusercontent.com/77481029/104824153-d1c5e480-584f-11eb-8c65-046b592abb35.png)

Ver aqui pantalla 6.0 

https://www.figma.com/file/KQoA5vmLkUrLJjAvDoLB4v/MVP?node-id=201%3A2

**Comment by wixo** [comment]
closed in #33
