### ISSUE TITLE
 Funcionalidad de elegir/eliminar a candidato para mis favoritos

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#135]
El usuario puede seleccionar al candidato dentro de sus favoritos, que deben ser guardados (local). 

Para agregar, se puede presionar sobre el boton "Agregame a tus favoritos" o en la estrella.  

Una vez el candidato es agregado a los favoritos, la pantalla cambia (pantalla 9). El boton te deja removerlo tambien

Pantallas 8 y 9. https://www.figma.com/file/v06bEacvbC9CI5jX0dmtJV/Votu_1.0?node-id=10%3A542

![image](https://user-images.githubusercontent.com/77481029/108003674-c0f5c380-6ff3-11eb-8efa-3ad033f35663.png)

**Comment by wixo** [comment]
closed in #192
