### ISSUE TITLE
Agregar Hotjars 

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#15]
Queremos poder trackear como esta usando el usuario a votu con mapas de calor. Para esto vamos a usar https://www.hotjar.com/ que permite inclusive grabar sesiones.

Agregar UTMs

Paste the Hotjar code into the <head> of every page you wish to track visitors and collect feedback. And then your installation.

```<!-- Hotjar Tracking Code for My site -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2235835,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>```

**Comment by wixo** [comment]
![giphy](https://user-images.githubusercontent.com/324686/104854972-cfa76880-58d7-11eb-94a4-487b57ee6a0d.gif)

**Comment by wixo** [comment]
Se agregó una primera versión de Hotjars, se pueden ver sus mensajes en la consola.
Importante: hice el deploy desde aquí, si todo bien entonces podremos seguir usándolo de esta manera si no ya nos enteraremos de como usarlo.

**Comment by wixo** [comment]
closed in https://github.com/openpolitica/open-wizard/pull/123
