### ISSUE TITLE
Entrar a "mis favoritos"

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#170]
El usuario debe poder entrar a sus favoritos desde la pantalla de partidos. Esta opcion te aprece cuando elegiste a un candidatx como favoritx. 

![Screen Shot 2021-02-22 at 23 20 22](https://user-images.githubusercontent.com/77481029/108778095-29e5ba00-7565-11eb-9987-bdfef810568c.png)

**Comment by wixo** [comment]
closed in https://github.com/openpolitica/open-wizard/pull/193
