### ISSUE TITLE
Update pantalla de resultados

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#21]
Una vez que el usuario ve la pantalla de partidos, ahora puede hacer click sobre un partido en especifico y ver resultados desglosados.  

Notese hay un count de cuantos candidatos hay y el nombre del partido. 

https://www.figma.com/file/v06bEacvbC9CI5jX0dmtJV/Votu_1.0?node-id=0%3A1

<img width="123" alt="Screenshot 2021-02-02 at 20 24 50" src="https://user-images.githubusercontent.com/77481029/106651759-e36bf380-6594-11eb-901b-2050ee67c632.png">

<img width="201" alt="Screenshot 2021-02-02 at 20 25 42" src="https://user-images.githubusercontent.com/77481029/106651792-eb2b9800-6594-11eb-97bf-f3cbd83c403f.png">

**Comment by wixo** [comment]
Esta tarea será dividida en 3 PRs

**Comment by wixo** [comment]
Estatus

- [X] Filtros se mantienen en el cambio de pantalla
- [X] Filtros se mantienen al volver a pantalla de partidos en el modal
- [X] Filtros se mantienen al volver a pantalla de partidos en los resultados
- [X] Cambios en el modal del filtro en la pantalla de candidatos debería afectar a lo que se está viendo en pantalla
- [X] Alertas indicando estados de los partidos (bloqueado porque falta la info del API)

Los 3 primeros items resueltos en https://github.com/openpolitica/open-wizard/pull/71
Cambios en el modal: https://github.com/openpolitica/open-wizard/pull/80
Alertas: https://github.com/openpolitica/open-wizard/pull/87

**Comment by wixo** [comment]
Este Issue se cerró con los 3 PRs indicados arriba 🥳
