### ISSUE TITLE
Update a texto en la pantalla de resultados

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#296]
Queremos hacer énfasis que la compatibilidad es basada en los planes de gobierno. Por eso el texto debe cambiar a "Plan de gobierno más compatible en: " 

<img width="412" alt="Screen Shot 2021-03-28 at 11 49 28" src="https://user-images.githubusercontent.com/77481029/112748415-b7308a00-8fbb-11eb-8922-d4856845aa27.png">

Ver issue #297 que pide incluir los tags de los ejes que el usuario marca. 

https://www.figma.com/file/NcTbjOqejUTk74m7mMyGmZ/VOTU_Wireframes?node-id=0%3A1

**Comment by wixo** [comment]
closed in https://github.com/openpolitica/open-wizard/pull/303
