### ISSUE TITLE
Agregar tags de los ejes que seleccionó el usuario en la pantalla de resultados

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#297]
El usuario quiere ver en los resultados qué ejes eligio para evitar que haya alguna confusion con sus intereses. 

Para esto se va a agregar unos tags de los ejes elegidos. 

<img width="412" alt="Screen Shot 2021-03-28 at 11 49 28" src="https://user-images.githubusercontent.com/77481029/112748467-0d9dc880-8fbc-11eb-8aba-3b3b5d8f9137.png">

Ver issue #296 que esta relaccionado con el cambio de texto en la oracion.

**Comment by wixo** [comment]
closed in https://github.com/openpolitica/open-wizard/pull/303
