### ISSUE TITLE
Poder marcar multiples opciones en algunas preguntas del cuestionario presidentes

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#300]
A trabajar lunes - martes, para que se puedan hacer suficientes tests. 

En la logica: 
- Si seleccionas un no me interesa - se borra el multi-select

**Comment by gianpietro1** [comment]
- La propiedad adicional que viene del API en cada pregunta es `isMultiple` (boolean)
- La propiedad adicional que viene del API en cada respuesta de tipo "Ninguno" (gob2,sal4) es `forceSingle` (boolean)

**Comment by wixo** [comment]
cerrado en #315
