### ISSUE TITLE
Se cambia el texto "selecciona una opcion" a texto dinamico

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#301]
Una vez que issue #300 se implemente, se debe cambiar el texto de instrucciones a dinamico: 
- single select: "selecciona una de las opciones" 
- multiple select: "selecciona maximo dos opciones" 
- 
Hemos agregado la indicación debajo de la pregunta para ambas casuísticas: single select y multiselect.
https://www.figma.com/file/dvjQTP1M7jaqKux81qfjSx/VOTU_UI?node-id=414%3A49

**Comment by gianpietro1** [comment]
La propiedad adicional que viene del API en cada pregunta es `isMultiple` (boolean)
