### ISSUE TITLE
Omitir se vuelve ilimitado y se agrega mensaje en caso que omitas todo

### ISSUE THREAD

**Issue by redsii** [openpolitica/open-wizard#302]
Ahora peudes omitir todo lo que quieras. Si es que el usuario decide omitir todo en todos los ejes, vera un mensaje: 

<img width="436" alt="Screen Shot 2021-03-28 at 14 53 07" src="https://user-images.githubusercontent.com/77481029/112752868-62017200-8fd5-11eb-91a0-29bb2678af29.png">

(Pantalla "results_sinresultados") 
https://www.figma.com/file/NcTbjOqejUTk74m7mMyGmZ/VOTU_Wireframes

**Comment by wixo** [comment]
closed in #319
