### ISSUE TITLE
Conteo de candidatos desde API

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/open-wizard#60]
Para hacer la cuenta dinámica:
![image](https://user-images.githubusercontent.com/10046142/106892867-aef25780-66ba-11eb-8599-05b2481e1377.png)

@wixo este cambio implicará modificar el candidatesUrl global para retirarle el trailing "?", porque la ruta del contador es "/candidates/count", así que esperaré a que los demás PRs pasen para poder arreglar el impacto en todos los archivos que usan candidatesUrl (tendremos que pasar un "?" antes de apiTerms)

**Comment by wixo** [comment]
Hola, tengo una pregunta media ingenua, pero: por qué necesitamos traer ese número desde un count de la BD? es decir, la lista va a seguir creciendo y va a cambiar de alguna manera? por que si son 3120 la mayoría del tiempo, no conviene que quede estático así nos ahorramos un call al API?
