### ISSUE TITLE
Botón "X" de cierre de FilterModal a veces no responde

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/open-wizard#94]
![IMG_5C609F447106-1](https://user-images.githubusercontent.com/10046142/107228134-4d97f480-69ea-11eb-89ab-3233606f725a.jpeg)

**Comment by AlmeAld** [comment]
Puede ser porque está haciendo fetch de los filtros seleccionados. Pienso que un botón de listo que esté fijo podría mejorar esto, además que estaríamos mejorando la experiencia de usuario. Aquí una idea.

![image](https://user-images.githubusercontent.com/60791759/107272881-5acdd700-6a1c-11eb-813e-43d0e989141b.png)

![image](https://user-images.githubusercontent.com/60791759/107272770-307c1980-6a1c-11eb-960f-48e3713875d1.png)
